rename files if copied in session as reference and correlate
TomographicImaging/iDVC pull request #186
Opened 2023-03-09 20:06 UTC by paskino

closes #184

2023-03-27 08:38 UTC, lauramurgatroyd requested changes
I found this does not work for tiffs - I get the following error:
![image](https://user-images.githubusercontent.com/60604372/227887314-bb41974a-27e8-432f-922c-3c11f3da612c.png)

And on the command line it gives an error: "When reading multiple files, all files must TIFF formatted."

I believe what is happening is it copies every tiff file to have the same new name, so they all overwrite each other.

2023-03-27 08:38 UTC, lauramurgatroyd commented on src/idvc/dvc_interface.py
> +                        new_file_dest = os.path.join(new_file_name + "mha")
```suggestion
                        new_file_dest = os.path.join(new_file_name + ".mha")
```

2023-03-30 16:23 UTC, paskino commented
I think I fixed the behaviour, but see also #193

2023-04-03 13:05 UTC, lauramurgatroyd requested changes
I encountered a couple of issues:

- When I encountered an error when clicking "Visualise" [I think the error was due to trying to downsample a compressed .mha file? ]  I had the error message pop up, but the progress dialog remained in place.

- Issues with .mhd files,  as the .mha created is compressed so can't be read by the resample reader. [ see comment ]

2023-04-20 13:59 UTC, lauramurgatroyd commented
Just fixed this issue:

> When I encountered an error when clicking "Visualise" [I think the error was due to trying to downsample a compressed .mha file? ] I had the error message pop up, but the progress dialog remained in place.

2023-04-20 14:33 UTC, lauramurgatroyd approved these changes

2023-04-20 14:34 UTC, merged