Set omp threads
TomographicImaging/iDVC pull request #194
Opened 2023-03-31 21:48 UTC by paskino

closes #171

2023-04-02 10:56 UTC, paskino commented
Merge after #186

2023-04-03 13:46 UTC, lauramurgatroyd requested changes
Could also be good to add some info on this new setting to the docs
https://tomographicimaging.github.io/iDVC/viewer.html#downsampling-settings

2023-04-03 13:48 UTC, lauramurgatroyd commented on src/idvc/dvc_interface.py
> +
Sorry, having reread the issue https://github.com/TomographicImaging/iDVC/issues/171, I understand why!

2023-04-03 13:49 UTC, lauramurgatroyd commented on src/idvc/dvc_interface.py
> +
It could be good to have some info in the settings window or as a tool tip recommending to set this lower than the total number of cores

2023-04-03 13:58 UTC, lauramurgatroyd commented
How can I check to see if this is being set as expected?

2023-04-04 22:18 UTC, paskino commented
> How can I check to see if this is being set as expected, when I change the number and run through the GUI?

This is a setting that affects only for the dvc executable. I really don't know how to check this.

2023-04-19 19:56 UTC, lauramurgatroyd approved these changes
Looks good!

2023-04-19 19:56 UTC, merged