Block dockwidgets
TomographicImaging/iDVC pull request #217
Opened 2024-01-10 17:24 UTC by paskino

Uses flag `NoDockWidgetFeatures` which prevents a lot of complications in handling `QDockWidgets` and makes the GUI more static.

Closes #174 
Closes #178

Tested on Windows.

2024-01-15 14:03 UTC, DanicaSTFC requested changes

2024-02-03 00:34 UTC, paskino commented on src/idvc/dvc_interface.py
all done except the title of the 2D viewer, see above

2024-02-16 10:20 UTC, DanicaSTFC commented on src/idvc/dvc_interface.py
- Before registration, if we right click on the tabs '2D Viewer', 'Help', 'Image information', the list of tabs appears and it is possible to show and hide the "Registration tab" (which has not been created yet). During the registration, the "Image Registration" tab appears. This is still floatable, movable and closable. 

Please hide the list and set the registration tab to 'NoDockWidgetFeatures'.

- In "6 - DVC results" > Display Graphs >The tabs "...Subvolume..." and "Summary" are floatable, movable and closable. 

This is unchanged. For consistent style my preference would be to set it to 'NoDockWidgetFeatures'.

2024-02-16 17:22 UTC, DanicaSTFC commented
@paskino We need to remove default popupMenu by overloading createPopupMenu in the viewer.

2024-02-20 10:17 UTC, DanicaSTFC approved these changes

2024-02-20 10:21 UTC, merged