consume CharEvents s and w in viewers
TomographicImaging/iDVC pull request #218
Opened 2024-01-12 12:27 UTC by paskino

closes #179 

Adds parsing of CLI parameters to idvc executable. 

Currently adds the way to set the global logging level.

2024-01-15 17:05 UTC, DanicaSTFC approved these changes
I tested this on windows.

The "w" key seems to do nothing. 

The "s" key now only shows/hides the slice in the 3D viewer (no extra behaviour).

This looks good to me and can be merged. I added a minor comment on the CHANGE file.

2024-01-15 17:05 UTC, DanicaSTFC commented on CHANGES.md
The order could change as 

`Consume events 's' and 'w' in viewers to avoid render changes between surface and wireframe resepectively.` 

Are the events consumed only in 3D or also in 2D?

2024-01-15 17:15 UTC, DanicaSTFC requested changes
When I run the app the terminal shows:
- "Unhandled event w" when "w" is pressed in the 3D viewer.
Can we change this so this is not printed? I noticed this sentence is printed for most keys pressed in the 3D viewer.

When I pressed "q" on the 3D viewer the app stopped responding. Is this something similar to the w behaviour we could avoid?

2024-01-16 08:08 UTC, paskino commented
The prints "unhandled event w" comes from the viewer, so it should be updated there.

`q` would stop the interactor processing loop. However, in the case where the viewer is in a Qt application, this should not have any effect, as the processing loop is handled by Qt.

I'll investigate.

2024-01-16 09:27 UTC, DanicaSTFC approved these changes

2024-01-17 16:40 UTC, merged