build: add pip dependencies
TomographicImaging/iDVC pull request #233
Opened 2024-04-30 12:20 UTC by casperdcl

- fixes #215

2024-04-30 19:09 UTC, paskino reviewed
The cilviewer is a dependency but it is not available in pypi and the build fails. How do we proceed?

2024-05-01 12:33 UTC, casperdcl commented
I added an ultra basic test (actually try to import something!) and was missing `libgl-dev` to `import vtk`.

ready to merge now :)

2024-05-21 16:26 UTC, DanicaSTFC requested changes

2024-05-21 16:26 UTC, DanicaSTFC commented on src/idvc/__init__.py
> +    import ccpi.viewer
The viewer has been moved to https://github.com/TomographicImaging/CILViewer. Can we update this?

2024-05-24 14:04 UTC, paskino approved these changes

2024-05-24 15:54 UTC, DanicaSTFC commented on src/idvc/__init__.py
> +    import ccpi.viewer
Apparently the conda is still called ccpi so my comment is not relevant.

2024-05-28 09:40 UTC, DanicaSTFC approved these changes

2024-05-28 09:42 UTC, merged